### ISSUE TITLE
Invalid SRH token returns 500 error

### ISSUE THREAD

**Issue by jahands** [hiett/serverless-redis-http#10]
Heya! Super cool project :)
One thing I noticed is that sending a request with an invalid token using `@upstash/redis` returns a 500 error, with this in the SRH logs:
```
﻿Using port 80
﻿Token resolver started
﻿Loaded config from env. 1 entries.
﻿00:33:22.502 [error] #PID<0.1202.0> running Srh.Http.BaseRouter (connection #PID<0.1201.0>, stream id 1) terminated
﻿Server: redis.uuid.rocks:80 (http)
﻿Request: POST /
﻿** (exit) an exception was raised:
﻿** (FunctionClauseError) no function clause matching in Srh.Http.ResultEncoder.encode_response/1
﻿(srh 0.1.0) lib/srh/http/result_encoder.ex:4: Srh.Http.ResultEncoder.encode_response({:not_authorized, "Invalid token"})
﻿(srh 0.1.0) lib/srh/http/base_router.ex:36: Srh.Http.BaseRouter.do_command_request/2
﻿(srh 0.1.0) lib/plug/router.ex:246: anonymous fn/4 in Srh.Http.BaseRouter.dispatch/2
﻿(telemetry 1.1.0) /app/deps/telemetry/src/telemetry.erl:320: :telemetry.span/3
﻿(srh 0.1.0) lib/plug/router.ex:242: Srh.Http.BaseRouter.dispatch/2
﻿(srh 0.1.0) lib/srh/http/base_router.ex:1: Srh.Http.BaseRouter.plug_builder_call/2
﻿(plug_cowboy 2.5.2) lib/plug/cowboy/handler.ex:12: Plug.Cowboy.Handler.init/2
﻿(cowboy 2.9.0) /app/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
```
Not a big deal, though.
Looked into fixing it, but elixir is very new to me. If you can point me in the right direction, I'd be happy to try fixing it!

**Comment by hiett** [comment]
Hey! Thanks for reporting. This should be a simple fix.

The ResultEncoder isn't taking into account the authentication errors. This means there is no function that matches this case, which is causing the error:

https://github.com/hiett/serverless-redis-http/blob/master/lib/srh/http/result_encoder.ex

Then, a case to send back different HTTP content can be added here:

https://github.com/hiett/serverless-redis-http/blob/dc233b2007127f66483280cae9067d2f3bebc8d4/lib/srh/http/base_router.ex#L70C14-L70C14

Let me know if you have any questions. I'm happy to point you in the right direction in writing it. On the other hand, if you don't feel like it, let me know and I'll put a fix together :)

Thanks for your time!
Scott

**Comment by jahands** [comment]
Thanks! I think I got it figured out in #11

**Comment by hiett** [comment]
Closed as merged.
