### ISSUE TITLE
Unicode encoding issues and sorted sets

### ISSUE THREAD

**Issue by kldavis4** [hiett/serverless-redis-http#20]
I'm using a sorted set to order some keys and running into some issues

I am using encodeURIComponent / decodeURIComponent to prevent mangling of keys - something like:

```
zadd<string>(this.zKey, { score: 0, member: encodeURIComponent(key) })
```

Then I use zrange to get the ordered keys. The problem is that the encoding changes the lexical order of the keys. For example, if I put these keys in:

```
[ '', '\t', '🐄', '12', '2', 'a', 'a🐄', 'b', 'd', 'e', 'f', 'ff', '~']
```

The correct lexical ordering should be:
```
[ '', '\t', '12', '2', 'a', 'a🐄', 'b', 'd', 'e', 'f', 'ff', '~', '🐄']

```
But if I encode the keys, the order is:
```
[ '', '\t', '🐄', '12', '2', 'a', 'a🐄', 'b', 'd', 'e', 'f', 'ff', '~']
```

If I don't encode the values, the keys get mangled:
```
[ '', '\t', '12', '2', 'a', 'a=\x04', 'b', 'd', 'e', 'f', 'ff', '~', '=\x04']
```

I have [confirmed](https://github.com/upstash/upstash-redis/issues/400) that this does not happen when using a real @upstash redis instance.

**Comment by hiett** [comment]
Thanks for reporting! Have you been able to replicate this behaviour by just directly running the commands in Redis via redis-cli?
SRH aims to be "transparent" in the sense that it shouldn't have any say in modifying the results, but it does do some base64 encoding on the HTTP layer when talking to Upstash's Redis SDK.
So I want to isolate the problem to SRH and ensure this isn't the underlying Redis instance (as Upstash isn't actual Redis, it's their own implementation, so there are subtle differences)

**Comment by kldavis4** [comment]
@hiett I'll try it directly with redis cli and let you know the results

**Comment by kldavis4** [comment]
@hiett I used the redis cli and I am seeing the same behavior so it doesn't look like SRH is actually the problem. I am using redis:6-bullseye - I'll try updating and retry the test (I think I ran into a docker-related issue with new versions)

**Comment by hiett** [comment]
@kldavis4 Okay - this makes sense. Try the latest Redis (Upstash technically targets 6.2, but some of their command behaviour is that of 7), but regardless I think this is a Redis issue. There are a number of commands across the board that are slightly different in Upstash as the Redis.io specs for commands can be very vague. So it might be that Upstash have not implemented it exactly how Redis operates, but at the same time the Redis.io docs might be so vague it's not clear about what to do in this edge case

**Comment by hiett** [comment]
I think you're right in that in the end - you shouldn't have to encode the values. I doubt @upstash/redis is at fault here for doing anything under the hood, as that would likely do the exact same to SRH. It has no idea that it is running against SRH rather than Upstash's server.
I think this is likely something under the hood for how Upstash's redis implementation works? Detecting its uri encoded would be a little weird though, and is definitely out of the domain of what Redis would normally do?
