### ISSUE TITLE
Make port configurable

### ISSUE THREAD

**Issue by aplr** [hiett/serverless-redis-http#21]
I want to run SRH in Cloud Run as a sidecar container, and it just feels weird that the redis connector blocks port 80 per default.

I tried to configure the port with `SRH_PORT` and `PORT` env vars, but for both SRH started with `Using port 80`. I saw in the code that in some case you're getting it from the env, but I guess not in the prod configuration.

Do you think it makes sense to make the port configurable, best case with the `PORT` env var?

And, thanks for the great project!

**Comment by hiett** [comment]
You're right in that it does look for an env var, but it's an elixir compile time one based on the prod profile. I will see if I have some time later to make this configurable at runtime.

**Comment by aplr** [comment]
Thanks for the quick reply, got it! Yea no worries and there's no time pressure, it's working with `80`, just thought it might be cleaner to make it configurable :)
