### ISSUE TITLE
Is there an example of using HTTP operations with Redis?

### ISSUE THREAD

**Issue by zqzzq** [hiett/serverless-redis-http#31]
I have deployed redis and serverless-redis-http [via-docker-compose](https://github.com/hiett/serverless-redis-http?tab=readme-ov-file#via-docker-compose), but I don't find how to use HTTP to call it, is there a simple example? Thanks.

**Comment by hiett** [comment]
Hi, the easiest ways to get started are using one of Upstash's SDKs. They are compatible with SRH. 
See the TypeScript SDK here: https://upstash.com/docs/oss/sdks/ts/redis/getstarted

You can see the internals of making HTTP calls directly here: https://upstash.com/docs/redis/features/restapi#post-command-in-body

However, please note that SRH only implements sending the command in the POST body. The Path method (e.g. /GET/NAME) will not work.

**Comment by zqzzq** [comment]
Thank you very much. I know how to use it now.
