### ISSUE TITLE
Incorrect encoding in response

### ISSUE THREAD

**Issue by jamesarosen** [hiett/serverless-redis-http#7]
I have a simple key in my Redis instance:
```
127.0.0.1:6379> set foo bar
OK
127.0.0.1:6379> get foo
"bar"
```

When I configure `@upstash/redis` to use serverless-redis-http, I get back a corrupted value:
```
await redis.get('foo')
'm�'
```

That second character is the Unicode replacement character. This suggests `@upstash/redis` is expecting UTF-8, but serverless-redis-http is returning something else.

I do notice that the [content-type](https://github.com/hiett/serverless-redis-http/blob/31b770cd9aa448e66d81768be9d7abc867698bc2/lib/srh/http/base_router.ex#L76) doesn't have an encoding marker.

**Comment by jamesarosen** [comment]
Upstash's [guide on hashed responses](https://docs.upstash.com/redis/sdks/javascriptsdk/troubleshooting#hashed-response) solves the issue:

```js
redis = Redis.fromEnv({ responseEncoding: false })
```

This might be nice to add to the README.

**Comment by hiett** [comment]
The README has been updated to reflect the responseEncoding disabling, I have spoken to someone at Upstash and have the basics required for me to implement the response encoding into Serverless Redis HTTP. I'm going to turn this issue into the PR to add that implementation.

Here are the requirements for me to implement it (From chronark at Upstash)

encoding is enabled by sending `Upstash-Encoding: base64` in the request header

Two response fields, as standard
```
{ result: ..., error: string or omitted }
```

the error field is untouched by encoding, but the result field is returned differently
- numbers are returned as numbers, for example:
  { result: 1 }
- null is also kept as is
  { result: null }
- strings and blobs are encoded
  { result: base64(result)}
- elements in arrays are encoded individually
  { result: [base64(e1), base64(e2), null, base64(3), 5] }

**Comment by chronark** [comment]
Hi, let me know if you run into issues. I collected this from a thread on slack but I hope everything is still accurate

**Comment by hiett** [comment]
Fantastic news! It is working.

[https://github.com/hiett/serverless-redis-http/actions/runs/4558707874/jobs/8041879367](Actions test suite for upstash/redis)

The only tests that are failing are JSON ones, whereby I am using Redis Stack for JSON, and the Upstash implementation might be slightly different. I am looking into this regardless, as some of the array responses are backwards - which might be on me, as in Elixir when doing array logic it's easy to get it backwards.

You can use the image today with `hiett/serverless-redis-http:0.0.5-alpha`, but over the coming days I'm going to clean it up, finalise my PR and release it as 0.0.5.

**Comment by jamesarosen** [comment]
I'm impressed! 👏

**Comment by chronark** [comment]
@hiett I'll dm you some internals from our slack regarding this
